version: '3'
services:
  my-postgres:
    image: postgres
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./dbscript.sql:/docker-entrypoint-initdb.d/create_tables.sql
  spring-boot-springdata-backend-service:
    image: project2-backend
    build: .
    ports:
      - 9999:4040
    depends_on:
      - my-postgres
    links:
      - my-postgres
 
  